### ISSUE TITLE
[BUG] ClassCastException in Training > Training when scrolling in top left panel

### ISSUE THREAD

**Issue by vorgbardo** [ho-dev/HattrickOrganizer#2304]
**Describe the bug**
Using any scrolling method in the top left panel in the Training > Training tab causes ClassCastException error to occur.

**To Reproduce**
1. Go to Training > Training. 
2. Resize the panes, including the top left pane.  NOTE: If you have trouble replicating this bug, keep on resizing the panes so that top left pane is affected (e.g., in ways that one of the scroll bars in the top left pane is removed, then again so that it is added). If you still have trouble replicating, try switching between max / restored app window size and redo the steps.
3. Attempt to scroll the contents of the top left pane with any method (e.g., by using either the vertical or horizontal scroll bar, or by hovering the mouse over it and using mouse scroll wheel).
4. java.lang.ClassCastException occurs and error dialog is shown.

**Screenshots**
Here is a screenshot of the location & the error, with the pane in which the error occurs marked with purple border: https://i.imgur.com/ILNTcxX.png

**Platform information:**
 - OS: Windows
 - Version: 7, Service Pack 1

**HO version:**
9.1

**Additional context**
Occurs every time after it has once occurred while HO is open. I got it temporarily fixed by itself when closing & reopening HO and downloading updated data, but an error when scrolling in the offending panel always occurs again after some resizing of the panels (albeit the error may be a differerent one, see comment below). Scrolling in all other panes in this and other tabs functions fine, even after resizing them.

**Comment by vorgbardo** [comment]
Managed to get rid of the bug for a minute by closing & reopening HO and downloading new data, but it reoccurred just like before (same steps). This time the error is different: https://i.imgur.com/pANsH7e.png

**Comment by wsbrenk** [comment]
@vorgbardo I can't reproduce the error, but based on the provided logs, the new beta version should fix the error. It would be great if you could try it out.

**Comment by vorgbardo** [comment]
@wsbrenk Tested with the latest JRE beta, couldn't reproduce with it, so presumably this will indeed be fixed in the next version. I'll get back to you if for some reason the bug persists in it.
